/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single frame in the split-file store. */
export interface JsFrame {
  frameId: number
  uri?: string
  title?: string
  createdAt: number
  status: string
  supersedes?: number
  tags: any
  content: string
}
/** Search hit from full-text search. */
export interface JsLexHit {
  frameId: number
  score: number
  matchCount: number
}
/** Search hit from vector similarity search. */
export interface JsVecHit {
  frameId: number
  score: number
}
/** Result of a compaction operation. */
export interface JsCompactResult {
  originalFrames: number
  activeFrames: number
  removedFrames: number
}
/** Split-file Memvid store: `.mv2d` (JSONL) + `.mv2x` (binary index). */
export declare class SplitStore {
  /**
   * Open or create a split store at the given `.mv2d` path.
   * The `.mv2x` index file is created alongside automatically.
   */
  constructor(mv2DPath: string)
  /** Append a text frame. Returns the assigned frame_id. */
  put(content: string): number
  /** Append a frame with full metadata. */
  putFrame(content: string, uri?: string | undefined | null, title?: string | undefined | null, tags?: any | undefined | null): number
  /** Get a frame by ID. */
  get(frameId: number): JsFrame | null
  /** Delete a frame (append tombstone). */
  delete(frameId: number): number
  /** Update a frame (append new version with supersedes). */
  update(oldFrameId: number, newContent: string): number
  /** Get all active frames. */
  activeFrames(): Array<JsFrame>
  /** Get the latest active frame (e.g., current prompt version). */
  latestActive(): JsFrame | null
  /** Full-text search. */
  lexSearch(query: string, limit: number): Array<JsLexHit>
  /** Vector similarity search. */
  vecSearch(query: Array<number>, limit: number): Array<JsVecHit>
  /** Add a precomputed embedding vector for a single frame. */
  addVec(frameId: number, embedding: Array<number>): void
  /** Build the vector index from a batch of (frame_id, embedding) pairs. */
  buildVecIndex(frameIds: Array<number>, embeddings: Array<Array<number>>): void
  /** Rebuild the full-text (lex) index from all active frames. */
  rebuildLexIndex(): void
  /** Persist the current index to `.mv2x`. */
  flushIndex(): void
  /** Full index rebuild from `.mv2d`. */
  rebuildIndex(): void
  /** Compact: remove tombstoned and superseded frames. */
  compact(): JsCompactResult
  /** Total frame count (including inactive). */
  get frameCount(): number
  /** Active frame count. */
  get activeFrameCount(): number
  /** Tombstone ratio (0.0 - 1.0). */
  get tombstoneRatio(): number
}
